__include__: [
  '../../../dataset/baseline2-background.yml',
  '../../../runtime.yml',
  '../../include/dataloader_640.yml',
  '../../include/optimizer.yml',
  '../../include/dfine_hgnetv2_640.yml',
]

output_dir: ./output/m-baseline2-background-2


DFINE:
  backbone: HGNetv2

HGNetv2:
  name: 'B2'
  return_idx: [1, 2, 3]
  freeze_at: -1
  freeze_norm: False
  use_lab: True
  pretrained: False

DFINETransformer:
  num_layers: 4  # 5 6
  eval_idx: -1  # -2 -3

HybridEncoder:
  in_channels: [384, 768, 1536]
  hidden_dim: 256
  depth_mult: 0.67

optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.000015625
    -
      params: '^(?=.*backbone)(?=.*norm|bn).*$'
      lr: 0.000015625
      weight_decay: 0.
    -
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn|bias)).*$'
      weight_decay: 0.

  lr: 0.000015625
  betas: [0.9, 0.999]
  weight_decay: 0.000125


epochs: 80 # Early stop
train_dataloader:
  dataset:
    transforms:
      policy:
        epoch: 74
  collate_fn:
    stop_epoch: 74
    ema_restart_decay: 0.9999
    base_size_repeat: 6

ema:
  warmups: 0

lr_warmup_scheduler:
  warmup_duration: 0
