task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 5 # your dataset classes
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /workspace/datasets/week2/baseline2-background-to-kaggle/train/images
    ann_file: /workspace/datasets/week2/baseline2-background-to-kaggle/train/train.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 20
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction

val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /workspace/datasets/week2/baseline2-background-to-kaggle/val/images
    ann_file: /workspace/datasets/week2/baseline2-background-to-kaggle/val/val.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 20
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction
