
train_dataloader:
  dataset:
    transforms:
      ops:
        - {type: RandomPhotometricDistort, p: 0.5}
        # - {type: RandomZoomOut, fill: 0, side_range: !!python/tuple [1, 1.5]}
        - {type: RandomIoUCrop, p: 0.8}
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: RandomHorizontalFlip}
        - {type: RandomRotate90, p: 0.5}
        - {type: Resize, size: [960, 960], }
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: ConvertPILImage, dtype: 'float32', scale: True}
        - {type: ConvertBoxes, fmt: 'cxcywh', normalize: True}
      policy:
        name: stop_epoch
        epoch: 72
        ops: ['RandomPhotometricDistort', 'RandomIoUCrop']

  collate_fn:
    type: BatchImageCollateFunction
    base_size: 960
    base_size_repeat: 3
    stop_epoch: 72

  shuffle: True
  total_batch_size: 12
  num_workers: 8

val_dataloader:
  dataset:
    transforms:
      ops:
        - {type: Resize, size: [960, 960], }
        - {type: ConvertPILImage, dtype: 'float32', scale: True}
  shuffle: False
  total_batch_size: 48
  num_workers: 8
