print_freq: 200
output_dir: './logs'
checkpoint_freq: 5


sync_bn: True
find_unused_parameters: False


use_amp: True
scaler:
  type: GradScaler
  enabled: True


use_ema: True
ema:
  type: ModelEMA
  decay: 0.9999
  warmups: 1000

use_wandb: False
project_name: D-FINE # for wandb
exp_name: baseline2-background-syn-1-1 # wandb experiment name
